### ISSUE TITLE
Install bug

### ISSUE THREAD

**Issue by BilliTheKid** [evdenis/selinux_permissive#1]
When I try to install version 2.0 it still states in Magisk it's version 1. Any ideas?

**Comment by BilliTheKid** [comment]
Ok, it's just Magisk bis stating it's an old version and I'm getting a pop
up now and then stating bits out of date.

**Comment by evdenis** [comment]
I've updated zip archive here https://github.com/evdenis/selinux_permissive/releases/tag/v2.0
Now it should display v2.

**Comment by BilliTheKid** [comment]
Thanks Denis.

I really appreciate it.

Cheers

W.
